### ISSUE TITLE
Need ability to specify compiler settings to use with dependencies

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1221]
### Overview

https://github.com/safe-global/safe-contracts uses a pretty wide pin for their contracts of anything in solc 0.7.x or 0.8.x series. However, the contracts only compile with 0.7.6 specifically. When specifying a dependency like this, it would be nice to be able to add additional config options to force it to compile with those specific options.

### Specification

```yaml
dependencies:
  - name: safe-contracts
    github: safe-global/safe-contracts
    version: 1.3.0
    settings: # or `config` maybe?
      # Configuring `ape-solidity` so this project compiles
      solidity:
        version: 0.7.6
```

These options would override whatever default config that Ape uses when compiling a dependency.

### Dependencies

n/a
