### ISSUE TITLE
Support NPM dependencies [APE-851]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1327]
### Overview

Some projects follow extremely poor quality standards and don't tag or publish their code on github at all, preferring to use NPM instead for hosting. No matter how bad of a decision I think this is, projects do it, so it would be helpful to be able to source these packages from NPM for the purposes of working with a particular dependency

### Specification

```yaml
- name: bad-dependency
  npm: @gnosis.pm/safe-singleton-factory
  version: 1.0.3
```

https://linear.app/apeworx/issue/APE-851/support-npm-dependencies
