### ISSUE TITLE
Specify Dependencies

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#149]
### Overview
Allow users to specify dependencies via `ape-config.yaml`

### Specification
```yaml
dependencies:
    dep1_name: https://github.com/org/dep1_name.git 
    dep2_name: ipfs://bafybeic5cdjintzeuegosx2y3nc27p3t7rfetj4pa5lprcylbfwytdllia
    ... # other types
```
