### ISSUE TITLE
Refactor plugins key for config file

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#151]
```yaml
plugins:                                                                                        
    ape-solidity: 0.1.0a2
```
Would rather it look more like this
```yaml
plugins:                                                                                        
    - solidity:          
        version: 0.1.0a2  # optional
```
