### ISSUE TITLE
Allow dev versus prod plugins

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#1519]
### Overview

Sometimes, I may not need all these fancy testing plugins like hardhat and stuff if my job for the project is run a few scripts.
It may be convenient at some point to allow installing only the prod plugins versus only the dev plugins.

### Specification

config like:

```yaml
plugins:
  dev:
    - name: hardhat
  
  prod:
    - name: ledger
    - name: alchemy
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
