### ISSUE TITLE
TestAccounts array isn't shown when getting value out of array size. [APE-1174]

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#1532]
### Environment information

- OS: macOS
- Python Version: 3.10.12
```
0.6.12

Installed Plugins:
  vyper        0.6.9
  hardhat      0.6.10
  solidity     0.6.7
  foundry      0.6.12
  tokens       0.6.1
  etherscan    0.6.7
  infura       0.6.2
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```
name: poc
plugins:
  - name: solidity
  - name: hardhat
  - name: infura
  - name: tokens
  - name: etherscan


ethereum:
  default_network: mainnet-fork
  mainnet:
      default_provider: infura
  mainnet_fork:
    default_provider: hardhat
```

### What went wrong?

Please include information like:

```
File: tests/conftest.py

import pytest
from ape import Contract, project

@pytest.fixture(scope="session")
def owner(accounts):
    yield accounts[10]

```

When executing a test, the file `accounts[10]` fail and display the `accounts` configured but not the one used in testing.

### How can it be fixed?

The error should show the array that corresponds to the test accounts.
