### ISSUE TITLE
Regression in `ape networks list` command.

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#163]
Regression in `ape networks list` command.

Command:

```
ape networks list
```

Actual output:

```
ecosystems:
- name: ethereum  # Default
  - name: mainnet
    providers:
    - http  # Default
  - name: ropsten
    providers:
    - http  # Default
  - name: kovan
    providers:
    - http  # Default
  - name: rinkeby
    providers:
    - http  # Default
  - name: goerli
    providers:
    - http  # Default
  - name: development  # Default
    providers:
    - http  # Default
    - test
    - hardhat
```

Expected output:

```
ecosystems:
- name: ethereum  # Default
  - name: mainnet
    providers:
    - http  # Default
  - name: ropsten
    providers:
    - http  # Default
  - name: kovan
    providers:
    - http  # Default
  - name: rinkeby
    providers:
    - http  # Default
  - name: goerli
    providers:
    - http  # Default
  - name: development  # Default
    providers:
    - http  # Default
    - test
    - hardhat
```
