### ISSUE TITLE
Fork at block height

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1740]
### Overview

Add an optional `block_number` kwarg (that accepts negative index height) which allows `network.fork` calls to connect to a fork at a specific block height

### Specification

```py
with networks.fork("provider", block_number=-100):
    ...  # create a fork 100 blocks ago
```

### Dependencies

N/a

**Comment by salparadi** [comment]
This would be awesome... is a nice feature of brownie to be able to set up a fork-atblock network and then easily pass a block # in during a script's execution. Hope this gets implemented!

**Comment by fubuloubu** [comment]
> This would be awesome... is a nice feature of brownie to be able to set up a fork-atblock network and then easily pass a block # in during a script's execution. Hope this gets implemented!

I believe you can do this with config, same as with Brownie. Is there a Brownie feature that I don't know about that let's you ad-hoc fork at a block height like that?

**Comment by salparadi** [comment]
Maybe I misunderstood the feature. My thinking was that in brownie I can create two "fork" networks. One that was just from current block (mainnet-fork) and then one that was at a specific block height (mainnet-fork-atblock), Passing in the block number to ganache>infura. On command line I'd just export BLOCK="18720551" before loading the console, and in a script I'd set os.environ["BLOCK"] = "18720551" then load the network.

```
  - name: Ganache-CLI (Mainnet Fork at Block)
    id: mainnet-fork-atblock
    cmd: ganache-cli
    host: http://127.0.0.1
    explorer: https://api.etherscan.io/api
    timeout: 120
    cmd_settings:
      chain_id: 1
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: grayGlacier
      mnemonic: brownie
      fork: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID@$BLOCK
```

My understanding in Ape is there can't be multiple forks for a provider like foundry. Maybe I can accomplish what I'm after though with this. If I just want to fork at current height, just set BLOCK=. Setting it to nothing?

```
foundry:
  host: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: https://rpc.ankr.com/eth
        block_number: ${BLOCK}
```
