### ISSUE TITLE
Cannot compile OpenZeppelin 5.x as a dependency

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1817]
### Environment information

- OS: macOS
- Python Version: 3.10 
- `ape` and plugin versions: 0.7.3

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```
name: Terms Of Service

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.1

solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/5.0.1"

plugins:
  - name: solidity
    version: 0.7.0
```

### What went wrong?

Please include information like:

OpenZeppelin 5.x does not work with ape.

```shell
ape pm compile -v debug
DEBUG: 'tmpeosen690' is not an 'ApeProject', but attempting to process as one.
WARNING: Compiled manifest produced no contract types! Are you missing compiler plugins?
SUCCESS: Package 'OpenZeppelin@5.0.1' compiled.

# No files are compiled, scanned, or created
```

### How can it be fixed?

Downgrade to OpenZeppelin 4.x.

**Comment by antazoey** [comment]
I am confused, it looks like it is work? The last line in your output is

```
SUCCESS: Package 'OpenZeppelin@5.0.1' compiled.
```

What is the part that makes this not working?

**Comment by antazoey** [comment]
For some reason I am not able to reproduce, it compiled fine for me.

**Comment by antazoey** [comment]
Do you have `ape-solidity` installed?

**Comment by rafael-abuawad** [comment]
Encountered the same issue while trying to use [solmate](https://github.com/transmissions11/solmate).

This is my `ape-config.yaml`
```yaml
name: demo

plugins:
  - name: solidity
    version: 0.7.0

dependencies:
  - name: smartcontractkit
    github: smartcontractkit/chainlink-brownie-contracts
    version: 0.8.0
  - name: solmate
    github: transmissions11/solmate

solidity:
  version: 0.8.23
  import_remapping:
    - "@chainlink/contracts=smartcontractkit/0.8.0"
    - "@solmate=solmate"
```
 
Yeah, I didn't specify the version, but Ape created a folder for the latest v6. Even if I define the version using `version: 6` or `ref: "v6"` it doesn't work


Made a repo with minimum code, that yields the same result https://github.com/rafael-abuawad/super-duper-journey

**Comment by rafael-abuawad** [comment]
I cannot downgrade solmate to `v5` because there isn't a `v5`, I wasn't able to find a workaround for this issue yet.

**Comment by antazoey** [comment]
I mean, why are specifying the solidity version (0.7) in your ape-config? That is what I am curious about. Arent the OZ contracts mostly on 0.8?

Either way, I havent been able to reproduce yet!
You shouldn't have to downgrade.

**Comment by antazoey** [comment]
your config is missing some things actually, i will open a PR against your repo that i had to do in order to get it to compile

**Comment by rafael-abuawad** [comment]
@antazoey, I'm specifying the ape-solidity plugin version as 0.7.0

```yaml
plugins:
  - name: solidity
    version: 0.7.0
```

But the Solidity version is the latest one.
