### ISSUE TITLE
Forks from ad-hoc connections should default to the ad-hoc network rather than a random one

### ISSUE THREAD

**Issue by smye** [ApeWorX/ape#1937]
### Overview

When performing an ad-hoc fork, default to the current network provider rather than a random one such as Tenderly or Flashbots/MevBlocker

- Current behaviour for the running the below code with `--networks http://192.168.1.18:8545/` is to use a random provider for forks
    ```python
    from ape import networks
    
    print("About to fork....")
    with networks.fork(provider_name="foundry"):
            ...
    
    ```
    This results in using a remote note instead of the local one supplied

  ```bash
  INFO: Connecting to existing Geth node at http://192.168.1.18:8545/[hidden].
  About to fork...
  INFO: Starting 'anvil' process.
  INFO: Connecting to existing Geth node at https://rpc.flashbots.net/[hidden].
  INFO: Stopping 'anvil' process.
  ```

- To override this behaviour, you must specify the upstream provider explicitly in `ape-config.yaml`. However, I think this would make sense if this was the default functionality
  ```yaml
  foundry:
    fork:
      ethereum:
        mainnet:
          upstream_provider: "http://192.168.1.18:8545"
  ```
