### ISSUE TITLE
feat: add support to migrate from ape-config.yaml to pyproject.toml

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#2141]
### Overview

Want to remove the need for ape-config.yaml to an ape key under the pyproject.toml for the configuration of an ape project.

### Specification

```toml
[tool.ape]
contracts_folder = "contracts"

[[tool.ape.dependencies]]
name = "openzeppelin"
github = "OpenZeppelin/openzeppelin-contracts"
version = "x.x.x"

[[tool.ape.plugins]]
name = "hardhat"

[[tool.ape.plugins]]
name = "solidity"
version = "0.8.1"
```

### Dependencies

#2142
