### ISSUE TITLE
Ape command fails to execute

### ISSUE THREAD

**Issue by ShubhamChndrvnshi** [ApeWorX/ape#2154]
### Environment information

- OS: macOS (m1)
- Python Version: 3.9.5
- `ape` and plugin versions:
eth-ape==0.8.2
ape-solidity==0.8.0
ape-hardhat==0.8.0
ape-etherscan==0.8.0
ape-infura==0.8.0

```sh
$ ape --version
# ...copy and paste result of above command here...

$ ape plugins list
# ...copy and paste result of above command here...
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
name: olas-opinion-market
contracts_folder: src
plugins:
  - name: solidity
  - name: hardhat
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.2
solidity:
  version: 0.8.24
  via_ir: True
hardhat:
  host: 127.0.0.1:8545
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 100
deployments:
  ethereum:
    sepolia:
      - contract_type: PrivateVote
        address: "0x6b12a13dbe488fd4b2e01eef819aadc245bb8ee6"
default_ecosystem: ethereum

```

### What went wrong?

Please include information like:

- what command you ran
Github actions were failing for ape test. Turns out ape command in not able to run.
Ran: ape --version, ape test, etc.
- the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
- full output of the error you received
ape --version
Traceback (most recent call last):
  File "/home/harambe/venv/bin/ape", line 5, in <module>
    from ape._cli import cli
  File "/home/harambe/venv/lib/python3.9/site-packages/ape/__init__.py", line 10, in <module>
    from ape.managers.project import ProjectManager as Project
  File "/home/harambe/venv/lib/python3.9/site-packages/ape/managers/__init__.py", line 6, in <module>
    from .chain import ChainManager
  File "/home/harambe/venv/lib/python3.9/site-packages/ape/managers/chain.py", line 10, in <module>
    import pandas as pd
  File "/home/harambe/venv/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/harambe/venv/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/harambe/venv/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/harambe/venv/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/harambe/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/harambe/venv/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by ShubhamChndrvnshi** [comment]
Installing numpy==1.26.4 solves this issue.
On 16th June 2024 bumpy release new version 2.0.0, which is causing the pandas code to break. 
Ape is using pandas and thus everything is breaking.

**Comment by antazoey** [comment]
Strange, you think the CI/CD today would be failing because of this but that does not seem to be the case.

**Comment by ShubhamChndrvnshi** [comment]
Below is the GitHub workflow that fails.
Tried to run ape in my local docker setup, there also getting the same error.
```yaml
name: Combined Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs do not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ape-test:
    name: Ape Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ape tests
        id: run_ape_tests
        run: ape test -s

```
