### ISSUE TITLE
Detect config setup for projects like snekmate

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#2299]
### Describe

I want to not have to config override snekmate like this:

```yaml
- pypi: snekmate
 config_override:
      base_path: src
      contracts_folder: snekmate
``` 

I want ape to automatically detect that structure somehow.

### Specification

new config would just be:

```yaml
- pypi: snekmate
```
