### ISSUE TITLE
Log type in ecosystem#decode_logs does not match RPC result for Blast network

### ISSUE THREAD

**Issue by unbanksy** [ApeWorX/ape#2456]
### Have you ensured that all of these are up to date?

- [X] Ape
- [ ] Ape plugins

### What version of Ape are you on?

0.8.24

### Operating System

macOS (Apple Silicon)

### Description

This line: https://github.com/ApeWorX/ape/blob/820249b8689082f82e4f5e668494c06870cb2257/src/ape_ethereum/ecosystem.py#L975

fails with 'str' object has no attribute 'get' and when you print out what logs actually is, it's: logs =  {'jsonrpc': '2.0', 'id': 10, 'result': []}. ie library is expecting an array but RPC returns dict instead. 

This is for querying Blast mainnet with Alchemy RPC. I used to use Quicknode RPC without issue.

My ape-config below:

## ape-config.yaml 
```yaml
foundry:
  uri: "http://127.0.0.1:8545"
  request_timeout: 60
alchemy:
  blast:
    mainnet:
      ws_uri: "wss://blast-mainnet.g.alchemy.com/v2/mykey"
      http_uri: "https://blast-mainnet.g.alchemy.com/v2/mykey"
node:
  base:
    mainnet:
      # ws_uri: "wss://snowy-solemn-dust.base-mainnet.quiknode.pro/mykey/"
      http_uri: "https://snowy-solemn-dust.base-mainnet.quiknode.pro/mykey/"
      transaction_acceptance_timeout: 120
      node:
        timeout: 60
  blast:
    mainnet:
      http_uri: "https://tiniest-omniscient-meadow.blast-mainnet.quiknode.pro/mykey/"
      transaction_acceptance_timeout: 120
      node:
        timeout: 60
networks:
  custom:
     - name: mainnet-tenderly
       chain_id: 69420
       ecosystem: blast
       base_ecosystem_plugin: optimism
plugins: 
  - name: foundry
  - name: etherscan
  - name: blast
  - name: base
```

### Reproduction code

```
from ape import chain, networks, Contract

networks.parse_network_choice("blast:mainnet:alchemy").__enter__()

transfers = Contract("0xb1a5700fa2358173fe465e6ea4ff52e36e88e2ad").Transfer.range(0, chain.blocks[-1].number)
list(transfers)
```
