### ISSUE TITLE
Duplicate ABI entries for proxied contract

### ISSUE THREAD

**Issue by derekpierre** [ApeWorX/ape#2569]
### Have you ensured that all of these are up to date?

- [x] Ape
- [x] Ape plugins

### What version of Ape are you on?

0.8.29

### Operating System

macOS (Intel)

### Ape Configuration

```yaml
name: nucypher-contracts
contracts_folder: contracts

plugins:
  - name: solidity
  - name: polygon
  - name: ape-etherscan

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.0
    config_override:
      solidity:
        version: 0.8.23
        evm_version: paris
  - name: openzeppelin-upgradeable
    github: OpenZeppelin/openzeppelin-contracts-upgradeable
    version: 5.0.0
  - name: fx-portal
    github: 0xPolygon/fx-portal
    version: 1.0.5
  - name: threshold
    github: threshold-network/solidity-contracts
    version: 1.2.1

solidity:
  version: 0.8.23
  evm_version: paris

ethereum:
  mainnet:
    transaction_acceptance_timeout: 600 # 10 minutes

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 40
```

### Description

When the ABI of a proxy contract is obtained, it contains duplicate ABI entries for the underlying implementation contract. I believe it is due to this function that tries to add the extra proxy ABIs to the existing implementation contract type, but ends up duplicating all implementation contract type ABIs - https://github.com/ApeWorX/ape/blob/v0.8.29/src/ape/managers/_contractscache.py#L927

I added a breakpoint during my testing at  https://github.com/ApeWorX/ape/blob/v0.8.29/src/ape/managers/_contractscache.py#L950. And here is the following debugging output:

```python
> /Users/derek/.local/share/virtualenvs/nucypher-contracts-mlay0-TM/lib/python3.11/site-packages/ape/managers/_contractscache.py(951)_merge_abis()
-> contract_type = base_contract.model_copy(deep=True)
(Pdb) extra_abis
...
(Pdb) n
> /Users/derek/.local/share/virtualenvs/nucypher-contracts-mlay0-TM/lib/python3.11/site-packages/ape/managers/_contractscache.py(952)_merge_abis()
-> contract_type.abi.extend(extra_abis)
(Pdb) contract_type
<ContractType Coordinator>
(Pdb) contract_type.abi
...
(Pdb) existing_entries = {abi.signature for abi in contract_type.abi}
(Pdb) new_entries = {abi.signature for abi in extra_abis}
(Pdb) existing_entries.difference(new_entries)
{'ProxyDeniedAdminAccess()', 'ERC1967InvalidAdmin(address admin)', 'ERC1967NonPayable()', 'ERC1967InvalidImplementation(address implementation)', 'AdminChanged(address previousAdmin, address newAdmin)', 'implementation() -> address', 'constructor(address _application)', 'Upgraded(address indexed implementation)'}
(Pdb) n
> /Users/derek/.local/share/virtualenvs/nucypher-contracts-mlay0-TM/lib/python3.11/site-packages/ape/managers/_contractscache.py(953)_merge_abis()
-> return contract_type
(Pdb) updated_entries = [abi.signature for abi in contract_type.abi]
(Pdb) no_dupes = set(updated_entries)
(Pdb) len(updated_entries)
295
(Pdb) len(no_dupes)
103
(Pdb) 
```

`existing_entries` for implementation contract and `new_entries` for proxy as only being the addition proxy ABIs, therefore they intersect on the implementation contract ABIs.

Consequently the final list of ABIs associated with the `contract_type` at the end ends up having overlaps signalled by the length of the list being longer than the length of the set.

We noticed this in our `nucypher-contracts` code because our contract registry entries that include ABIs included duplicates which we subsequently needed to filter out.

Take a look and let me know if I'm missing something or if it is a legit bug. We are using `ape` 0.8.29 and not 0.8.30 (latest).

### Reproduction code

Only internal test code. But basically the process is:
1. Deploy an implementation contract
2. Deploy a proxy contract (OpenZeppelin TransparentUpgradeableProxy) and set the target to be the implementation contract
(this may be sufficient, but our process did the following additional 3 steps)
3. Deploy another copy of the implementation contract
4. Upgrade the proxy contract from 2) to point to 3) instead
5. Look at ABI list (`contract_type.abi`) for the proxy contract.
