### ISSUE TITLE
Allow specifying deterministic deployments via single address

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#2590]
### Describe

Some contracts can be deployed to the same address on every chain, so it is much nicer to only have to specify them once in the config

### Specification

Specify in config via:
```toml
[[tool.ape.deployments.deterministic]]
contract_type = PullSplitFactory
address = 0x5cbA88D55Cec83caD5A105Ad40C8c9aF20bE21d1
```

Use it the same as with normal deployments:
```py
factory = project.PullSplitFactory.deployments[0]
```
