### ISSUE TITLE
Deployments config does not work with forked network

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#2594]
### Have you ensured that all of these are up to date?

- [x] Ape
- [x] Ape plugins

### What version of Ape are you on?

0.8.32

### What command(s) is the bug in?

`project.ContractType.deployments`

### Operating System

Linux

### Ape Configuration

```toml
[[tool.ape.deployments.ethereum.mainnet]]
contract_type = "PullSplitFactory"
address = "0x5cbA88D55Cec83caD5A105Ad40C8c9aF20bE21d1"
```

### Description

When using the `.deployments` feature on a fork network, Ape does not look to the upstream network to see if a deployment has already been made
