### ISSUE TITLE
Contract Inheritance using dependency contract causes contract compilation failures

### ISSUE THREAD

**Issue by derekpierre** [ApeWorX/ape#2610]
### Have you ensured that all of these are up to date?

- [x] Ape
- [x] Ape plugins

### Operating System

macOS (Apple Silicon)

### ape-config.yaml

```yml
name: nucypher

plugins:
  - name: solidity

dependencies:
  - name: nucypher-contracts
    github: derekpierre/nucypher-contracts
    ref: secreto
    config_override:
      solidity:
        version: 0.8.23
        evm_version: paris

  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.0

solidity:
  version: 0.8.23
  evm_version: paris

test:
  provider:
    chain_id: 131277322940537  # ensure ape doesn't change chain id to 1337
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 30
  balance: 1_000_000 ETH

```

### Description

There are two repositories involved:
- `nucypher-contracts`: Contains various Solidity contracts.
- `nucypher`: Uses Ape for testing, and imports contracts from `nucypher-contracts`.

In the acceptance tests within `nucypher`, we define a test contract like the following:
```solidity
import "@nucypher-contracts/contracts/coordination/<NuCypher-Contracts Contract>";

contract <NuCypher Test Contract> is <NuCypher-Contracts Contract> {
    ...
}
```

The test contract extends a contract from the `nucypher-contracts` repo (specifically, my fork at `derekpierre/nucypher-contracts`).

The ape-config.yaml in `nucypher` is configured to pull this dependency (see `ape-config.yaml` above).

However, extending a contract from nucypher-contracts triggers the following compilation error:
```bash
==================================== ERRORS ====================================
__________ ERROR at setup of test_get_agent_with_different_registries __________
/home/runner/work/nucypher/nucypher/tests/acceptance/conftest.py:131: in t_token
    _t_token = deployer_account.deploy(nucypher_dependency.TestToken, TOTAL_SUPPLY)
E   ape.exceptions.ApeAttributeError: 'LocalProject' object has no attribute 'TestToken'. Also checked extra(s) 'contracts'. However, there is a source file named 'TestToken.sol', did you mean to reference a contract name from this source file? Else, could it be from one of the missing compilers for extensions: .adoc?
        deployer_account = <TestAccount 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266>
        nucypher_dependency = <ProjectManager $HOME/.ape/packages/projects/derekpierre_nucypher-contracts/secreto>
```

`TestToken.sol` is an unrelated contract in `nucypher-contracts` and the contract is deployed as a fixture in the `conftest.py` for `nucypher` tests.

Once I changed the acceptance test contract to no longer extend the contract from `nucypher-contracts` i.e. the following instead
```solidity
contract <NuCypher Test Contract> {
   ...
}
```
the compilation error disappeared and the test passed successfully.

In summary, the compilation failure occurs in a non-obvious way—triggered by extending a contract from the dependency repo—even though the failing symbol (`TestToken`) is unrelated to the inheritance.
