### ISSUE TITLE
Allow specifying default network ecosystem, network, and provider in ape-config

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#321]
### Overview

Allow us to set a default value for ecosystem, network, and provider using the `ape-config.yaml` file.

### Specification

Maybe

```yaml
ethereum:
  development:
    default_provider: hardhat
```

but I am not sure.
