### ISSUE TITLE
Dependencies: Refactor dependencies config into key-value object

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#398]
Currently the keys are like:

```yaml
dependencies:
  MyDependency: github-org/github-repo@1.2.3
```

Which is not very scaleable to other types of dependencies from other locations

Suggestion to break it out a bit:
```yaml
dependencies:
  - name: MyDependency
    github: github-org/github-repo
    version: 1.2.3
```

At first, only `github` and `version` keys are specified. Eventually relax the requirement of `version` key to allow alternatives like `branch`, and then eventually add other types of dependencies such as `gitlab`, `ipfs`, `ipns`, etc.
