### ISSUE TITLE
Unprocessed Config Items are an Error, not a Warning

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#400]
If there are unrecognized keys in the config file, `ape` currently bails out during `ape plugins install`:

```bash
$ ape plugins install
ERROR: (ConfigError) Unprocessed config items.
```

This is the config file I was trying to use. `solidity:import_remappings` is the unrecognized key.

```yaml
plugins:
  - name: solidity

dependencies:
  OpenZeppelin: OpenZeppelin/openzeppelin-contracts@3.1.0

solidity:
    import_remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
```

What should instead happen is that the install proceeds, perhaps by noting the unrecognized keys during install, and then later on the keys are fine after the install because the plugin can now process them.
