### ISSUE TITLE
feat: handle migrating brownie projects

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#640]
### Environment information

```
$ ape --version
0.1.4

$ ape plugins list
Installed Plugins:
  vyper       0.1.0
  solidity    0.1.0
  hardhat     0.1.3

```

* Python Version: 3.8.12
* OS: macOS/linux/win: Mac Os

### What went wrong?

I have started a console to play around with the `project` object.
```
ape console
from ape import accounts, project
```

When trying to autocomplete using tab on `project.` I get the following error:

<img width="516" alt="Screen Shot 2022-04-07 at 10 28 19 AM" src="https://user-images.githubusercontent.com/87183122/162156312-b42c5809-61bf-4def-a631-53365248e45d.png">

On a side note, I have imported https://github.com/yearn/yearn-vaults/ into the project dependencies to be able to deploy a vault.

**Comment by pandadefi** [comment]
The ape-config.yaml

```
plugins:
  - name: solidity
  - name: vyper
  - name: hardhat

# require OpenZepplin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.5.0
  - name: vault
    github: yearn/yearn-vaults
    version: 0.4.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.5.0"

ethereum:
  local:
    default_provider: hardhat

```
