### ISSUE TITLE
ERROR: (ProjectError) Unknown version 'xxx' for repo 'xxx'.

### ISSUE THREAD

**Issue by PatrickAlphaC** [ApeWorX/ape#782]
### Environment information

* OS: macOS 
* Python Version: Python 3.9.5
* `ape` and plugin versions:
Ape:
- 0.2.7
- I have also tried on dev version 0.2.8

Plugins:
- solidity    0.2.3

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):
I have tested this with 2 configs:

```yaml
name: aave-stuff
contracts_folder: contracts
dependencies:
  - name: aave
    github: aave/protocol-v2
    version: 1.0.1
solidity:
  import_remapping:
    - "@aave=aave/1.0.1"
```

and (as recommended from https://github.com/ApeWorX/ape/issues/749#issuecomment-1139672651)

```yaml
dependencies:
  - name: chainlink
    github: smartcontractkit/chainlink-brownie-contracts
    version: 0.4.1
    contracts_folder: contracts/src/v0.4

solidity:
  import_remapping:
    - "@chainlink=chainlink/0.4.1"
```

### What went wrong?

For the aave stuff, I have a contract like so:

```javascript
// SPDX-License-Identifier: agpl-3.0
pragma solidity 0.6.12;

import {ILendingPoolAddressesProvider} from "@aave/contracts/interfaces/ILendingPoolAddressesProvider.sol";

interface ILendingPool {
    // rest of the contract...
}
```

For the chainlink stuff, I have a contract like so:

```javascript
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";

contract PriceFeedConsumer {}
```

When running `ape compile` in the aave stuff I get:

```
ERROR: (ProjectError) Unknown version '1.0.1' for repo 'protocol-v2'.
```

On the chainlink stuff I get:

```
ERROR: (ProjectError) Unknown version '0.4.1' for repo 'chainlink-brownie-contracts'.
```
