### ISSUE TITLE
Dependencies not importing correctly

### ISSUE THREAD

**Issue by PatrickAlphaC** [ApeWorX/ape#786]
### Environment information

* OS: macOS 
* Python Version: 3.9.5
* `ape` and plugin versions: 
* vyper 0.2.0
* ape 0.2.7

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
# ...copy and paste result of above command here...
```

```
name: apeworx-starter-kit
contracts_folder: contracts
dependencies:
  - name: chainlink
    github: PatrickAlphaC/chainlink-vyper
    branch: main
    contracts_folder: contracts
```

### What went wrong?

I have an interface at the repo in my dependencies:

```python
# @version ^0.3.3


@external
@view
def decimals() -> uint8:
    return 0


@external
@view
def description() -> String[1000]:
    return ""


@external
@view
def version() -> uint256:
    return 0


@external
@view
def getRoundData(_roundId: uint80) -> (uint80, int256, uint256, uint256, uint80):
    return (0, 0, 0, 0, 0)


@external
@view
def latestRoundData() -> (uint80, int256, uint256, uint256, uint80):
    return (0, 0, 0, 0, 0)
```

And I'm looking to access it in my contract in this project:

```
# @version ^0.3.3

import chainlink.AggregatorV3Interface as AggregatorV3Interface

price_feed: public(AggregatorV3Interface)

```

However, I can't get ape to recognize the `AggregatorV3Interface` contract.

Not sure what's going on.
